# -*- coding: utf-8 -*-
"""
This module sets the zone air temperatures for testcase multizone_office_complex_air.

"""


def compute_control(y, forecasts=None):
    """Compute the control input from the measurement.

    Parameters
    ----------
    y : dict
        Contains the current values of the measurements.
        {<measurement_name>:<measurement_value>}
    forecasts : structure depends on controller, optional
        Forecasts used to calculate control.
        Default is None.

    Returns
    -------
    u : dict
        Defines the control input to be used for the next step.
        {<input_name> : <input_value>}

    """
    
    HourOfDay = int((y['time']%86400)/3600)
    
    if (HourOfDay <= 6) or (HourOfDay > 21):
        THWSet = 273.15 + 80
        TSupAir1 = 273.15 + 12.88
        TSupAir2 = 273.15 + 14.18
    elif 15 <= HourOfDay < 18:
        THWSet = 273.15 + 75
        TSupAir1 = 273.15 + 15
        TSupAir2 = 273.15 + 15.18
    else:
        THWSet = 273.15 + 70
        TSupAir1 = 273.15 + 14
        TSupAir2 = 273.15 + 16.66

    u = {
	'hvac_floor1_TSupAirSet_u':TSupAir1,
	'hvac_floor1_TSupAirSet_activate':1,
	'hvac_floor1_dpSet_u':310,
	'hvac_floor1_dpSet_activate':0,
	'hvac_floor1_duaFanAirHanUnit_cooCoil_yCoo_u':0.5,
	'hvac_floor1_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
	'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor1_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor1_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor1_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor1_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor1_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor1_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonWes_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonWes_TZonCooSet_activate':0,
    'hvac_floor1_oveZonWes_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonWes_TZonHeaSet_activate':0,
    'hvac_floor2_TSupAirSet_u':TSupAir2,
    'hvac_floor2_TSupAirSet_activate':1,
    'hvac_floor2_dpSet_u':400,
    'hvac_floor2_dpSet_activate':0,
    'hvac_floor2_duaFanAirHanUnit_cooCoil_yCoo_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor2_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor2_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor2_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor2_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor2_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor2_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonWes_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonWes_TZonCooSet_activate':0,
    'hvac_floor2_oveZonWes_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonWes_TZonHeaSet_activate':0,
    'hvac_floor3_TSupAirSet_u':285.15,
    'hvac_floor3_TSupAirSet_activate':0,
    'hvac_floor3_dpSet_u':400,
    'hvac_floor3_dpSet_activate':0,
    'hvac_floor3_duaFanAirHanUnit_cooCoil_yCoo_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor3_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor3_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor3_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor3_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor3_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor3_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonWes_TZonCooSet_u':297.65,
	'hvac_floor3_oveZonWes_TZonCooSet_activate':0,
	'hvac_floor3_oveZonWes_TZonHeaSet_u':293.15,
	'hvac_floor3_oveZonWes_TZonHeaSet_activate':0,
	'hvac_oveChiWatSys_TW_set_u':279.65,
	'hvac_oveChiWatSys_TW_set_activate':0,
	'hvac_oveChiWatSys_dp_set_u':400000,
	'hvac_oveChiWatSys_dp_set_activate':0,
	'hvac_oveHotWatSys_TW_set_u':THWSet,
	'hvac_oveHotWatSys_TW_set_activate':1,
	'hvac_oveHotWatSys_dp_set_u':250000,
	'hvac_oveHotWatSys_dp_set_activate':0
    }

    return u


def initialize():
    """Initialize the control input u.

    Parameters
    ----------
    None

    Returns
    -------
    u : dict
        Defines the control input to be used for the next step.
        {<input_name> : <input_value>}

    """
    
    u = {
	'hvac_floor1_TSupAirSet_u':288.65,
	'hvac_floor1_TSupAirSet_activate':1,
	'hvac_floor1_dpSet_u':410,
	'hvac_floor1_dpSet_activate':1,
	'hvac_floor1_duaFanAirHanUnit_cooCoil_yCoo_u':1,
	'hvac_floor1_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
	'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor1_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor1_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor1_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor1_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor1_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor1_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor1_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor1_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor1_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor1_oveZonWes_TZonCooSet_u':297.65,
    'hvac_floor1_oveZonWes_TZonCooSet_activate':0,
    'hvac_floor1_oveZonWes_TZonHeaSet_u':293.15,
    'hvac_floor1_oveZonWes_TZonHeaSet_activate':0,
    'hvac_floor2_TSupAirSet_u':285.15,
    'hvac_floor2_TSupAirSet_activate':0,
    'hvac_floor2_dpSet_u':400,
    'hvac_floor2_dpSet_activate':0,
    'hvac_floor2_duaFanAirHanUnit_cooCoil_yCoo_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor2_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor2_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor2_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor2_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor2_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor2_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor2_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor2_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor2_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor2_oveZonWes_TZonCooSet_u':297.65,
    'hvac_floor2_oveZonWes_TZonCooSet_activate':0,
    'hvac_floor2_oveZonWes_TZonHeaSet_u':293.15,
    'hvac_floor2_oveZonWes_TZonHeaSet_activate':0,
    'hvac_floor3_TSupAirSet_u':285.15,
    'hvac_floor3_TSupAirSet_activate':0,
    'hvac_floor3_dpSet_u':400,
    'hvac_floor3_dpSet_activate':0,
    'hvac_floor3_duaFanAirHanUnit_cooCoil_yCoo_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_cooCoil_yCoo_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yEA_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yEA_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yOA_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yOA_activate':0,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yRet_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_mixingBox_mixBox_yRet_activate':0,
    'hvac_floor3_duaFanAirHanUnit_oveSpeRetFan_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_oveSpeRetFan_activate':0,
    'hvac_floor3_duaFanAirHanUnit_supFan_oveSpeSupFan_u':0.5,
    'hvac_floor3_duaFanAirHanUnit_supFan_oveSpeSupFan_activate':0,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV1_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV2_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV3_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV4_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yDam_u':0.5,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yDam_activate':0,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yReaHea_u':0.5,
    'hvac_floor3_fivZonVAV_vAV5_oveZonLoc_yReaHea_activate':0,
    'hvac_floor3_oveZonCor_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonCor_TZonCooSet_activate':0,
    'hvac_floor3_oveZonCor_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonCor_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonEas_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonEas_TZonCooSet_activate':0,
    'hvac_floor3_oveZonEas_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonEas_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonNor_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonNor_TZonCooSet_activate':0,
    'hvac_floor3_oveZonNor_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonNor_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonSou_TZonCooSet_u':297.65,
    'hvac_floor3_oveZonSou_TZonCooSet_activate':0,
    'hvac_floor3_oveZonSou_TZonHeaSet_u':293.15,
    'hvac_floor3_oveZonSou_TZonHeaSet_activate':0,
    'hvac_floor3_oveZonWes_TZonCooSet_u':297.65,
	'hvac_floor3_oveZonWes_TZonCooSet_activate':1,
	'hvac_floor3_oveZonWes_TZonHeaSet_u':293.15,
	'hvac_floor3_oveZonWes_TZonHeaSet_activate':1,
	'hvac_oveChiWatSys_TW_set_u':281.95,
	'hvac_oveChiWatSys_TW_set_activate':0,
	'hvac_oveChiWatSys_dp_set_u':500000,
	'hvac_oveChiWatSys_dp_set_activate':0,
	'hvac_oveHotWatSys_TW_set_u':338.15,
	'hvac_oveHotWatSys_TW_set_activate':0,
	'hvac_oveHotWatSys_dp_set_u':250000,
	'hvac_oveHotWatSys_dp_set_activate':0
    }

    return u
