FROM project1-boptest-worker

# Build arguments
ARG VERSION=""

ENV HOME=/home/compiler

# Install common dependencies
RUN apt-get update \
    && apt-get install -y git-lfs \
    && apt-get install -y zip unzip \
    && . miniconda/bin/activate \
	&& conda update -n base -c defaults conda \
	&& conda activate pyfmi3 \
	&& python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip

# Install open-modelica
RUN export DEBIAN_FRONTEND="noninteractive" && echo "VERSION: $VERSION" && test ! -z "$VERSION" && apt-get update && apt-get upgrade -qy && apt-get dist-upgrade -qy \
    && apt-get install -qy gnupg wget ca-certificates apt-transport-https \
    && echo "deb https://build.openmodelica.org/omc/builds/linux/releases/$VERSION/ `cat /etc/lsb-release | grep CODENAME | cut -d= -f2` release" > /etc/apt/sources.list.d/openmodelica.list \
    && wget https://build.openmodelica.org/apt/openmodelica.asc -O- | apt-key add - \
    && apt-get update && apt-get upgrade && apt-get dist-upgrade \
    && apt-get install --no-install-recommends -qy omc cmake \
    && apt-get install omlibrary \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Add compiler user
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/compiler && \
    mkdir -p /etc/sudoers.d && \
    echo "compiler:x:${uid}:${gid}:compiler,,,:/home/compiler:/bin/bash" >> /etc/passwd && \
    echo "compiler:x:${uid}:" >> /etc/group && \
    echo "compiler ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/compiler && \
    chmod 0440 /etc/sudoers.d/compiler && \
    chown ${uid}:${gid} -R /home/compiler
USER compiler
WORKDIR ${HOME}

# Gather Modelica libraries
RUN mkdir $HOME/MODELICAPATH && mkdir git \
    && cd git \
    && git lfs install \
    && git clone https://github.com/ibpsa/modelica-ibpsa.git \
    && git clone https://github.com/open-ideas/IDEAS.git && cd IDEAS && git checkout 3fb1871 && cd .. \
    && git clone https://github.com/lbl-srg/modelica-buildings.git \
    && ln -s $HOME/git/IDEAS/IDEAS $HOME/MODELICAPATH/IDEAS \
    && ln -s $HOME/git/modelica-buildings/Buildings $HOME/MODELICAPATH/Buildings \
    && ln -s $HOME/git/modelica-ibpsa/IBPSA $HOME/MODELICAPATH/IBPSA

ENV MODELICAPATH=$HOME/MODELICAPATH/:$HOME/MODELICAPATH/IBPSA:$HOME/MODELICAPATH/IDEAS:$HOME/MODELICAPATH/Buildings
RUN mkdir $HOME/boptest
ENV PYTHONPATH=$HOME/boptest

WORKDIR /

CMD ["tail", "-f", "/dev/null"]
