# Dockerfile for unit testing
FROM ubuntu:24.04

# Set noninteractive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

# Install Python 3.9, venv and pip
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt update && \
    apt install -y \
        python3.10 \
        python3.10-venv \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Create non-sudo user "tester" and set working directory as new user's home
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/tester && \
    mkdir -p /etc/sudoers.d && \
    echo "tester:x:${uid}:${gid}:tester,,,:/home/tester:/bin/bash" >> /etc/passwd && \
    echo "tester:x:${uid}:" >> /etc/group && \
    echo "tester ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/tester && \
    chmod 0440 /etc/sudoers.d/tester && \
    chown ${uid}:${gid} -R /home/tester
USER tester
ENV HOME /home/tester
WORKDIR ${HOME}

# Create a Python virtual environment and install required Python packages
RUN mkdir .venvs && cd .venvs && python3.10 -m venv testing && . testing/bin/activate
# Ensure the virtual environment's bin directory is on the PATH
ENV PATH="${HOME}/.venvs/testing/bin:$PATH"
# Install python packages
RUN python -m pip install --upgrade pip && \
    python -m pip install pandas==2.3.3 numpy==2.2.6 requests==2.32.5 openapi-python-client==0.28.1

# Setup working directory
RUN cd ~/ && mkdir boptest
ENV PYTHONPATH="${HOME}/boptest:$PYTHONPATH"
WORKDIR ${HOME}/boptest

# Default script to run, needs to be defined when running the container (e.g. docker compose run --rm <container> <path/to/python_script.py>)
CMD []
