# -*- coding: utf-8 -*-
"""
This module implements unit tests testcase.py.

"""

import os
import unittest
import pandas as pd
import testcase
import utilities

testing_root_dir = os.path.join(utilities.get_root_path(), 'testing')

reference_result_directory = 'testcase'

class partialAdvance(utilities.partialChecks):
    '''Tests for the testcase.TestCase.advance API.

    The reference is generated by calling fmu.simulate, so running these with
    direct stepping checks that the two agree.

    '''

    def test_check_input_for_zero(self):
        '''Test that an overwrite value of 0 given in float is used.

        '''

        self.testcase.set_step(60)
        # Advance first wih fan speed of 0.5, then with fan speed of 0.0.
        u = {'fcu_oveFan_u': 0.5,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        u = {'fcu_oveFan_u': 0.0,
             'fcu_oveFan_activate':1}
        status, message, payload = self.testcase.advance(u)
        # Get results
        status, message, payload = self.testcase.get_results(['fcu_reaPFan_y', 'fcu_oveFan_u'],
                                                             0,
                                                             payload['time'])
        # Test results
        df = pd.DataFrame(payload).set_index('time')
        ref_filepath = os.path.join(testing_root_dir, 'references', reference_result_directory, 'check_input_for_zero.csv')
        self.compare_ref_timeseries_df(df, ref_filepath)

class Advance(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API through fmu.simulate.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu')
        self.assertFalse(self.testcase.direct_step,
                         'Direct stepping must be off unless asked for.')

class AdvanceDirectStep(unittest.TestCase, partialAdvance):
    '''Unit tests for the testcase.TestCase.advance API with direct stepping.

    Runs the same checks against the same references as ``Advance``, which were
    generated through fmu.simulate, so agreeing with them is what says the two
    simulate the same thing.

    '''

    def setUp(self):
        '''Set up for unit tests.  Uses bestest_air with direct_step=True.

        '''

        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        self.testcase = TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu',
                                 direct_step=True)
        self.assertTrue(self.testcase.direct_step)

class DirectStepOption(unittest.TestCase):
    '''Unit tests for how direct stepping is switched on.

    '''

    def test_default_is_off(self):
        '''Test that direct stepping is off unless it is asked for.

        '''

        self.assertFalse(self._make().direct_step)

    def test_argument_enables_it(self):
        '''Test that the argument switches direct stepping on.

        '''

        self.assertTrue(self._make(direct_step=True).direct_step)

    def _make(self, **kwargs):
        os.chdir(os.path.join(testing_root_dir))
        os.chdir('..')
        from testcase import TestCase
        return TestCase(fmupath='testcases/bestest_air/models/wrapped.fmu', **kwargs)


if __name__ == '__main__':
    utilities.run_tests(os.path.basename(__file__))
