name: CI

on:
  pull_request:
    branches:
      -  'boptest-service'
  push:
    branches:
      -  'boptest-service'
    tags:
      - '*-service'

jobs:
  simulation-tests:
    name: Run boptest simulation tests
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"   

      - name: Run test cases 
        run: |
          VERSION_PREFIX=MyPrefix
          echo Display the version prefix: $VERSION_PREFIX
          echo And use it multiple times: $VERSION_PREFIX
          PYTHONPATH=$GITHUB_WORKSPACE
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          ls -l
          echo PYTHONPATH $PYTHONPATH
          python --version
          #PYTHONPATH=$GITHUB_WORKSPACE python -c "import sys; print('\n'.join(sys.path))"
          PYTHONPATH=$GITHUB_WORKSPACE-c "import sys; print('\n'.join(sys.path))"
          python -c "import sys; print('\n'.join(sys.path))"
          PYTHONPATH=$GITHUB_WORKSPACE python examples/python/testcase1.py 

